<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Sara Customers</title>
</head>

<body>

<?php

/*
    Sara White
    CSD-440
    Assignment 5.2

*/

// customer arrays (fictional customer data generated by ChatGPT (OpenAI))
$customers = array(

    array("firstName" => "Anna", "lastName" => "Johnson", "age" => 28, "phone" => "402-555-1001"),

    array("firstName" => "David", "lastName" => "Miller", "age" => 35, "phone" => "402-555-1002"),

    array("firstName" => "Maria", "lastName" => "Lopez", "age" => 42, "phone" => "402-555-1003"),

    array("firstName" => "James", "lastName" => "Wilson", "age" => 31, "phone" => "402-555-1004"),

    array("firstName" => "Emily", "lastName" => "Davis", "age" => 24, "phone" => "402-555-1005"),

    array("firstName" => "Robert", "lastName" => "Anderson", "age" => 50, "phone" => "402-555-1006"),

    array("firstName" => "Lisa", "lastName" => "Taylor", "age" => 37, "phone" => "402-555-1007"),

    array("firstName" => "Michael", "lastName" => "Thomas", "age" => 29, "phone" => "402-555-1008"),

    array("firstName" => "Rachel", "lastName" => "Martin", "age" => 33, "phone" => "402-555-1009"),

    array("firstName" => "Kevin", "lastName" => "Brown", "age" => 45, "phone" => "402-555-1010")

);


// display customer arrays
echo "<h3>Customer List:</h3>";

foreach ($customers as $customer) {

    echo "<strong>Name:</strong> " . $customer["firstName"] . " " . $customer["lastName"] . "<br>";

    echo "<strong>Age:</strong> " . $customer["age"] . "<br>";

    echo "<strong>Phone Number:</strong> " . $customer["phone"] . "<br><br>";
}


// searching by last name
$lastNames = array_column($customers, "lastName");
$lastNameSearch = array_search("Wilson", $lastNames);

echo "<h3>Search by Last Name:</h3>";

if ($lastNameSearch !== false) {

    echo "<strong>Name:</strong> " . $customers[$lastNameSearch]["firstName"] . " " . $customers[$lastNameSearch]["lastName"] . "<br>";

    echo "<strong>Age:</strong> " . $customers[$lastNameSearch]["age"] . "<br>";

    echo "<strong>Phone Number:</strong> " . $customers[$lastNameSearch]["phone"] . "<br>";
}


// searching by age
$ages = array_column($customers, "age");
$ageSearch = array_search(37, $ages);

echo "<h3>Search by Age:</h3>";

if ($ageSearch !== false) {

    echo "<strong>Name:</strong> " . $customers[$ageSearch]["firstName"] . " "
     . $customers[$ageSearch]["lastName"] . "<br>";

    echo "<strong>Age:</strong> " . $customers[$ageSearch]["age"] . "<br>";

    echo "<strong>Phone Number:</strong> " . $customers[$ageSearch]["phone"] . "<br>";
}


// searching by phone number
$phoneNumbers = array_column($customers, "phone");
$phoneSearch = array_search("402-555-1003", $phoneNumbers);

echo "<h3>Search by Phone Number:</h3>";

if ($phoneSearch !== false) {

    echo "<strong>Name:</strong> " . $customers[$phoneSearch]["firstName"] . " " 
    . $customers[$phoneSearch]["lastName"] . "<br>";

    echo "<strong>Age:</strong> " . $customers[$phoneSearch]["age"] . "<br>";

    echo "<strong>Phone Number:</strong> " . $customers[$phoneSearch]["phone"] . "<br>";
}

?>

</body>
</html>

<!--
References

W3 Schools. (n.d.). PHP Arrays. https://www.w3schools.com/php/php_arrays.asp

W3 Schools. (n.d.). PHP array_search() Function. https://www.w3schools.com/php/func_array_search.asp

W3 Schools. (n.d.). PHP array_column() Function. https://www.w3schools.com/php/func_array_column.asp

Generation of fictional customer data:
OpenAI. (2026). ChatGPT (GPT-5.6 Sol) [Large language model]. https://chatgpt.com/

--!>